### ISSUE TITLE
0.5.3 Media Notification Manager

### ISSUE THREAD

**Issue by cklenk** [martijn00/XamarinMediaManager#449] opened 2019-04-22 21:43 UTC
## 💬 Questions and Help

With the new version 0.5.3. I was trying to find some documentation on how to update the Media Notification song information. If a new song comes on I'd like to update the song title and artist. In the previous versions you would call MediaNotificationManager.UpdateNotifications. I'm not seeing anything like that in 0.5.3. Any help or direction would be fantastic.

Thanks

**Comment by martijn00** [comment] 2019-04-26 12:56
If you set the information in the `MediaItem` it will be used to show in the notification.

**Comment by martijn00** [comment] 2019-05-16 08:33
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/439

**Closed by martijn00** 2019-05-16 08:33 UTC
Labels: enhancement
