### ISSUE TITLE
Initialize on xamarin.forms

### ISSUE THREAD

**Issue by georgemichailou** [martijn00/XamarinMediaManager#443] opened 2019-04-16 19:18 UTC
Hello and thanks for this plugin !!!

I create a new xamarin forms app but i have a problem on android.

![Screenshot at Apr 16 21-56-49](https://user-images.githubusercontent.com/14372162/56237588-031aea80-6095-11e9-9b82-71c8c8823d76.png)

I add Plugin.MediaManager.Forms 0.5.3 on all platforms. I use Xamarin.Forms 3.6.0.

Any available working xamarin forms sample or any tip how can i fix it ? 

Thanks!

**Comment by MrSerWin** [comment] 2019-04-16 19:23
@georgemichailou did you tried set target android framework version to 29? I helped me

**Comment by georgemichailou** [comment] 2019-04-16 19:26
> @georgemichailou did you tried set target android framework version to 29? I helped me

I use API level 27. It's not supported ?

**Comment by MrSerWin** [comment] 2019-04-16 19:28
@georgemichailou I'm not sure, but author of this lib gave me this advise. Probable not supported, or supported but api 29 for build is needed

**Comment by georgemichailou** [comment] 2019-04-16 19:34
@MrSerWin thanks for this. I search and I found here https://github.com/martijn00/XamarinMediaManager/issues/435 similar problems.

Waiting for the lib owner answer !!

**Comment by tonyyyrocks39** [comment] 2019-04-17 03:38
Dont expect too much from library author,he must be too much busy with other works..
He adviced me in this issue #437 "Please investigate and build up knowledge. This is not a problem in the library."

So I added a try catch in that specific line,it gave me detailed exception-
Exception is in MediaManager/CrossMediaManager.cs line number 27 which is
IMediaManager ret = implementation.Value;

so ret is null

futher more digging found that,in line 45-
#if NETSTANDARD
            return null;
#else

Not sure-

Also forget this message(This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation,they are just harcoding it ,you can see in that file),probably it is nothing related to actual exception,probably it is null reference excpetion.

**Comment by valentin-debris** [comment] 2019-04-17 07:59
The problem with the Init() is not due tothis library. I migrate from 0.4.5 to 0.5.3 without any problem for the init.

I also created a dummy repo [(https://github.com/valentin-debris/MediaManagerStates)](https://github.com/valentin-debris/MediaManagerStates) (to show another issue) but if you build it, you will see no problems, so it's not related to the library. Try to remove the bin & obj folder, and set target android framework version to 29

**Comment by tonyyyrocks39** [comment] 2019-04-17 09:43
@valentin-debris -Could you please tell,why in the line 45 its
#if NETSTANDARD
return null;
#else

May i am in wrong direction,but curious to know the answer for this

**Comment by valentin-debris** [comment] 2019-04-17 10:00
@tonyyyrocks39  I don't know why, I didn't participate to this library, I'm only using it !
But this is not the source of your problem because this is also in 0.4.5 (https://github.com/martijn00/XamarinMediaManager/blob/0.4.5/MediaManager/CrossMediaManager.cs).

If you try to reinstall the version 0.4.5, is it working ? You're probably missing a dependency somewhre :/

**Comment by tonyyyrocks39** [comment] 2019-04-17 10:18
yes..like I said If I use 0.4.5 ,its working like a charm,but a again due to recent updates in Android,seek,currenstatevaluechanged etc.. methods were not giving actual value,thats why I switched to 0.5.3...

**Comment by martijn00** [comment] 2019-04-17 10:50
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437

As explained there: you need to target Android 9.0, and on Android call `CrossMediaManager.Current.Init(this);`. Visual studio picks the .NET Standard code when the native platform is not available. When you target Android 8.1 the library will not load the correct assembly, and therefor show the error message.

**Closed by martijn00** 2019-04-17 10:50 UTC

**Comment by tonyyyrocks39** [comment] 2019-04-17 14:04
My sincere apologies to everybody,if i wasted time of somebody.
Everybody was Saying target to Android 9.0,
I thought its in Android=>Properties=>AndroidManifest.

But we need to change the target in Android=>Properties=>Application Tab=>Compile using Target version dropdown.

@MrSerWin -

Hopefully you are able to pick the Android 9.0.I was initially confused why I am not able to pick the Android 9.0 ,if I click the Dropdown in the Application tab,.
Because if I click the dropdown it It was showing Android 8.0,
I missed the scroller part,So when I scrolled it up ,I found Android 9.0 to select

Sorry again and Thanks all,I am able to get it work,
Trust me 200 dollars was pending due to this library,now i have lot of work to do...

Thanks,
Tony
