### ISSUE TITLE
Unable to play ios local videos on device

### ISSUE THREAD

**Issue by Ng-India99** [martijn00/XamarinMediaManager#190] opened 2017-05-05 07:24 UTC
hello,
I’m trying to play local videos, its working well on android, coming to ios when iam assigning media path to videoView source I’m getting **reference not set to an instance of an object** error on **MediaFailed event handler**. If I given source is http resource its working fine, problem with the only local videos.

**Error StackStrace:**
  at Plugin.MediaManager.VideoPlayerImplementation.OnMediaFailed () [0x00017] in <36b6ccc6927a4997a8ce5e9f38386937>:0 
  at Plugin.MediaManager.VideoPlayerImplementation+<Play>d__48.MoveNext () [0x0015b] in <36b6ccc6927a4997a8ce5e9f38386937>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase+<PrepareCurrentAndThen>d__79.MoveNext () [0x00100] in <9eb99f10a90a43b496d4125d286ef6be>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase+<<Play>b__70_0>d.MoveNext () [0x00062] in <9eb99f10a90a43b496d4125d286ef6be>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3969/8b53676d/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Plugin.MediaManager.Abstractions.Implementations.MediaManagerBase+<RaiseMediaFileFailedEventOnException>d__77.MoveNext () [0x0006a] in <9eb99f10a90a43b496d4125d286ef6be>:0

**code:**
private async void BtnPickVideo_Clicked(object sender, EventArgs e)
        {
            await CrossMedia.Current.Initialize();
            MediaFile file = null;
            file = await CrossMedia.Current.PickVideoAsync();
            if (file != null)
            {
                try
                {
                    UploadVideoView.Source = file.Path;
                    UploadVideoView.IsVisible = true;
                    UploadVideoView.Focus();
                    await this.MediaManager.Play();
                }
                catch (Exception ex)
                {
                 System.Diagnostics.Debug.WriteLine(ex.StackTrace);
                }
            }
        }
**File types:** .mov , .mp4
**Info plist :**
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>

**Comment by mrwcjoughin** [comment] 2017-07-24 15:12
I am getting the same issue. any assistance ?

**Comment by BillFulton** [comment] 2017-07-25 13:46
I saw an iOS post along roughly similar lines where the solution was to prepend "file://", but that's likely what you're already doing. Am interested because planning to use local video files myself. My files are previously downloaded, not in the bundle.

**Comment by mrwcjoughin** [comment] 2017-07-25 14:20
@BillFulton Yes I have tried that - without success. it looks like it may have been fixed in 0.0.5 - but i can't use that because I'm also using the .Forms package - and that doesn't support 0.0.5 yet :(

**Comment by BillFulton** [comment] 2017-07-26 00:38
@mrwcjoughin Hope it will be fixed soon then. Looks like a really great package  :)

**Comment by BillFulton** [comment] 2017-07-26 12:41
I also am unable to play local video or audio from iOS device, but my symptom is a bit different - the request is just ignored with no error. My local files are not in the bundle, they are in a subfolder of Library. My complete code is attached. For both video and audio, it works with web uri but not with file uri. Have not tried Android.
[ShowVideoPage.txt](https://github.com/martijn00/XamarinMediaManager/files/1176555/ShowVideoPage.txt)

**Comment by BillFulton** [comment] 2017-07-26 12:42
Re .-1, I should have mentioned it is in a Xamarin Forms PCL.

**Comment by mrwcjoughin** [comment] 2017-07-28 12:50
What i've done for now is use a webview and play the video through there using the HTML video tag - it works well

**Comment by Hungeberg** [comment] 2017-11-22 12:04
I can confirm that appending the file path with "file://" works for iOS with version 0.4.4 of this plugin.

if (Device.RuntimePlatform == Device.iOS)
{
    result = "file://" + file.Path;
}
else
{
    result = file.Path;
}

**Comment by antonioreyna** [comment] 2018-04-14 23:47
how do you embedded the video? i am having a similar problem but i notice the mp4 is not on my bundle

**Comment by antonioreyna** [comment] 2018-04-15 18:36
what would be the path for a video on android in Resources/raw? thanks

**Comment by mhdshbk** [comment] 2018-05-08 16:05
@Hungeberg Can you please give more details on that?
I tried prepending `file://` and worked on Android for playing local video.
But I'm not able to play video on iOS, downloaded to local storage using 
```
public string GetDownloadPath(string filename)
{
    string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
    var path = Path.Combine(documentsPath, filename);
    return path;
}
```
Thanks in advance! 🙂

**Comment by sw-ms-milangohil** [comment] 2018-08-23 06:14
I am able to play below url 
"https://ia800201.us.archive.org/12/items/BigBuckBunny_328/BigBuckBunny_512kb.mp4"
and Unable to play Youtube URL or Embedded YouTube URL like "https://youtu.be/luDyX0kYzY4" or "https://www.youtube.com/watch?v=luDyX0kYzY4" for that i need to change any thing or what how to play youtube url can you help me please

**Comment by BillFulton** [comment] 2018-08-24 00:38
So sorry, I do not have an idea on that.

**Closed** 2019-04-05 14:21 UTC
