### ISSUE TITLE
Repeat mode is not working.

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#576] opened 2019-08-06 15:45 UTC
###
```
//Constructor
  public VideoView()
        {
             InitializeComponent();
            events();
            PlayHLSVideoAsync();
            Repeat();
            setSpeed();
            setVolume();
        }

        private void events() {

            CrossMediaManager.Current.PositionChanged += PositionChangedFunc;
            CrossMediaManager.Current.StateChanged += StateChangedFunc;             
        }

        private void Repeat() {
            CrossMediaManager.Current.RepeatMode = RepeatMode.One;
            //CrossMediaManager.Current.VolumeManager.Balance = 1;
        }
```

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2019-08-06 17:07
Fill in a proper and full bug report or this will be closed.

**Comment by adambarath** [comment] 2019-08-07 07:40
Just a note: turning on shuffle mode also bugy on Android.

(MonoAndroid) MediaManagerImplementation overrides ShuffleMode like:

```
        public override ShuffleMode ShuffleMode
        {
            get
            {
                return (ShuffleMode)MediaController?.ShuffleMode;
            }
            set
            {
                MediaController?.GetTransportControls()?.SetShuffleMode((int)value);
            }
        }
```

But in the base class this property affects to MediaQueue:

```
        public virtual ShuffleMode ShuffleMode
        {
            get
            {
                return MediaQueue.ShuffleMode;
            }
            set
            {
                MediaQueue.ShuffleMode = value;
            }
        }
```

Shouldn't set the base class' property also in setter like?
```
            set
            {
                *base.ShuffleMode = value;*
                MediaController?.GetTransportControls()?.SetShuffleMode((int)value);
            }
```

Without calling *base.ShuffleMode = value;* it does no shuffles items in the media queue

**Comment by adambarath** [comment] 2019-08-07 07:42
I'm gonna check this issue and offer a fix idea.

**Comment by kishor010** [comment] 2019-08-07 09:54
@adambarath 
Okie cool.
Please let us know if any idea or fix.
Thank you.

**Comment by marcelovargas** [comment] 2019-08-09 00:35
Hi I have the same problem.
I cant repeat the playlist....

**Comment by adambarath** [comment] 2019-08-21 14:14
I started investigate the issue. Created a Xamarin Forms test page where you can reproduce it:

https://github.com/adambarath/XamarinMediaManager/tree/fix-repeatmode 

I'll create a PR if find a fix

**Comment by martijn00** [comment] 2019-08-21 14:17
The problem is that we have to sync the native Queue with the MediaManager Queue. It is easy to do this one way, from MediaManager to Native, but if shuffle is passed to the native system it is hard to sync the shuffled list back to Mediamanager.

My idea is that maybe I disable native shuffle, and instead handle it fully in MediaManager. Then when a shuffle is done, we simple sync the shuffled queue to the native queue.

**Comment by adambarath** [comment] 2019-08-24 10:56
> The problem is that we have to sync the native Queue with the MediaManager Queue. It is easy to do this one way, from MediaManager to Native, but if shuffle is passed to the native system it is hard to sync the shuffled list back to Mediamanager.
> 
> My idea is that maybe I disable native shuffle, and instead handle it fully in MediaManager. Then when a shuffle is done, we simple sync the shuffled queue to the native queue.

I aggree with you. iOS is a complete mess itself. I was not able to find any whole description about AVPlayerLooper and QueuePlayer, so I have a lot of questions about how to these tools on iOS. By the way I fixed the repeat and shuffle issues on iOS by handling all the stuff in AppleMediaPlayer class. I'll make a code cleaning and after that may I ask you kindly to review my code and code changes?

**Comment by martijn00** [comment] 2019-08-24 12:06
I'm happy to review any pr!

**Comment by adambarath** [comment] 2019-08-26 12:14
....aaand I noticed and interesting thing on Android. RepeatMode.One does not work. Is this bug report only about Android's repeatMode.One @kishor010 ?

**Comment by adambarath** [comment] 2019-08-26 12:35
@martijn00 did you know about Android RepeatMode.One issue?

**Comment by kishor010** [comment] 2019-08-27 13:59
> ....aaand I noticed and interesting thing on Android. RepeatMode.One does not work. Is this bug report only about Android's repeatMode.One @kishor010 ?

Its for both platforms (Android and iOS)
@martijn00

**Comment by kishor010** [comment] 2019-08-27 14:00
> ....aaand I noticed and interesting thing on Android. RepeatMode.One does not work. Is this bug report only about Android's repeatMode.One @kishor010 ?

Can we get this fix in latest version of plugin or do I need to add something in the code ?

**Comment by adambarath** [comment] 2019-08-27 14:01
I created a PR, so bug on iOS will be fixed by the next release after my PR got approved

**Comment by kishor010** [comment] 2019-08-27 14:01
> I created a PR, so bug on iOS will be fixed by the next release after my PR got approved

It's awesome.

**Comment by adambarath** [comment] 2019-08-31 15:02
@martijn00 , may I ask you kindly to review my PR https://github.com/martijn00/XamarinMediaManager/pull/599 ?

**Comment by kishor010** [comment] 2019-09-11 13:44
@martijn00 
Still not working in the latest version.

Even KeepScreenOn option is also not working.

**Comment by martijn00** [comment] 2019-09-11 13:45
Stop saying it is not working. I will close this issue when it is fixed.

**Closed** 2019-09-25 14:46 UTC
Labels: bug
