### ISSUE TITLE
[Android] Build failure around exoplayer2 notifications

### ISSUE THREAD

**Issue by karak** [martijn00/XamarinMediaManager#545] opened 2019-07-25 06:56 UTC
## 🔙 Regression

Build failed after I updated Xamarin.MediaManager from 0.5.3 to 0.7.4.

### Old (and correct) behavior

Build Success

### Current behavior

Build Failure with the following messages.

<pre>
  Xamarin.Android.Common.targets(2816, 3): java/lang/String;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: com.google.android.exoplayer2.ui.PlayerNotificationManager$MediaDescriptionAdapter.getCurrentSubText : (Lcom/google/android/exoplayer2/Player;)Ljava/lang/String;
</pre>

### Reproduction steps

1. Update XamarinMediaManager with Nuget.
2. Fix its codes to API, as rename MediaFile to MediaItem, Status to State, and change some event-handlers.
3. Try to build

AppManifest doesn't say minSdkVersion is 13, but 21.

```xml:
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />
```

### Configuration

**Version:** 0.7.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2019-07-25 09:24
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/524

**Closed by martijn00** 2019-07-25 09:24 UTC

**Comment by karak** [comment] 2019-07-26 12:54
Thank you. I changed the configuration.
