### ISSUE TITLE
Unhandled Exception:  System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation

### ISSUE THREAD

**Issue by Muthutc** [martijn00/XamarinMediaManager#476] opened 2019-05-19 08:32 UTC
While i am try to play a audio file in Xamarin forms Application I got this error.

Unhandled Exception:  System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation

![image](https://user-images.githubusercontent.com/39237441/57979670-b7b27e00-7a3e-11e9-8be8-f8c18cd68cdf.png)

**Comment by martijn00** [comment] 2019-05-19 11:31
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437

**Closed by martijn00** 2019-05-19 11:31 UTC
