### ISSUE TITLE
TimeOut Exceeded 

### ISSUE THREAD

**Issue by ramprudvi** [martijn00/XamarinMediaManager#471] opened 2019-05-07 15:35 UTC
Unhandled Exception:

System.NotImplementedException: <Timeout exceeded getting exception details> occurred

**Comment by martijn00** [comment] 2019-05-07 15:40
Fill out the issue template.

Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437

**Closed by martijn00** 2019-05-07 15:40 UTC
