### ISSUE TITLE
Xamarin Forms UWP Video not rendered

### ISSUE THREAD

**Issue by dPritz** [martijn00/XamarinMediaManager#203] opened 2017-06-01 13:01 UTC
I'm using Visual Studio 2015 with Xamarin.Forms 2.3.4.231 and using the MediaManager with a PCL. When I start to play a video on UWP only Audio is running. The VideoView element is visible but not the native canvas.

Xaml is mostly used like this:

`        <Grid x:Name="MediaContainer">
            <forms:VideoView x:Name="VideoView" AspectMode="AspectFill" />
        </Grid>
`
Does somebody now about this issue? The VideoRenderer doesn't implement a Init method to call.
Thanks.

**Comment by jackd942** [comment] 2017-06-01 16:28
Having the same issue with VS 2017 and Xamarin.Forms 2.3.4.247. No video, but audio is fine.

**Comment by modplug** [comment] 2017-06-06 08:08
I've experienced the same problem on iOS when I didn't Init the VideoViewRenderer.

Try to initialize Xamarin.Forms like this in your UWP app
  
List<Assembly> assembliesToInclude = new List<Assembly>();
assembliesToInclude.Add(typeof(VideoViewRenderer).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assembliesToInclude); 

Please report back :)

**Comment by Steztric** [comment] 2017-06-12 17:40
Hi @modplug I also had the same problem in iOS. I just did  `new VideoViewRenderer();` in my Main.cs and it worked. Is there a better way? I couldn't work out how to do it by loading the assemblies manually like you did because the API is not the same in iOS.

**Comment by pengx** [comment] 2017-06-13 05:04
UWP doesn't work even with @modplug 's suggestion.
Video still not loading on UWP

**Comment by naice** [comment] 2017-06-16 16:58
Same here with UWP. :/

**Comment by JimSEOW** [comment] 2017-06-18 16:09
same here with UWP

**Comment by Steztric** [comment] 2017-06-18 21:00
Have you tried using `VideoViewRenderer.Init()` in your initialisation code?

**Comment by pengx** [comment] 2017-06-23 15:43
there is no VideoViewRenderer.Init()  on UWP

**Comment by managedcoder** [comment] 2017-07-09 14:17
I also have this same issue and to investigate I built the video example that James Montemagno created at https://github.com/jamesmontemagno/Hanselman.Forms and it has this same problem.  I do think it's strange that the docs say must call VideoViewRenderer.Init() or else you will suffer the exact problem we are discussing here and yet, there is not VideoViewRenderer.Init() for UWP.... is that the solution we are looking for... someone needs to expose the Init() API?  If James' code shows this same issue I think that's a pretty good indicator that this is a legit bug.

**Comment by dPritz** [comment] 2017-07-12 09:18
The actual issue is that the size of the VideoRenderer was initialised with an ActualWidth and Height of 0. The video was loading and playing correctly but just not visible. Should be fixable by slightly adapting the renderer for UWP

**Comment by einc** [comment] 2017-07-28 20:07
I'm having the same problem for Android. I've called VideoViewRenderer.Init() in my initialization code but 
I still only hear the audio. I tried setting HeightRequest="200"  and WidthRequest="100" but I still cannot see the video. Is there something else I can try?

**Comment by ThaineNorris** [comment] 2017-08-16 16:52
I have the same problem with UWP and Android. No video is displayed, though its audio is played. I tried forcing  window size in the UWP VideoViewRenderer. but that didn't help either.

**Comment by Onjay** [comment] 2017-09-18 12:37
I am having the same issue. The video will not render, but audio will play. I'm using 0.4.3, Plug.MediaManger.Forms, and Plugin.MediaManager. I've set a height and width in XAML for the control, with no effect. I've set UWP's App.xaml.cs to typeof(VideoViewRenderer).GetTypeInfo().Assembly, and/or Mainpage's new VideoViewRenderer(); with no effect.

**Comment by johnthiriet** [comment] 2017-09-18 13:16
I can confirm the same issue. I can't even debug the sample project since because of bait and switch I can't put a breakpoint inside the VideoViewRenderer class for UWP.

**Comment by jlevolution** [comment] 2017-12-15 20:58
I have the same problem with the call "VideoViewRenderer.Init();" in MainPage.xaml.cs UWP, there is no VideoViewRenderer.Init() on UWP. Version: 0.4.5

**Comment by GovardhanNag** [comment] 2018-04-12 12:09
Add below code in App.xaml.cs for UWP, which resolved my video rendering issue.

var assemblies = new List<Assembly>();
assemblies.Add(typeof(VideoViewRenderer).GetTypeInfo().Assembly);
Xamarin.Forms.Forms.Init(e, assemblies);

**Comment by CliffAgius** [comment] 2018-04-23 10:15
@GovardhanNag I have tried this but still no Init() and it's not working.  Are you using Forms or Xamarin.UWP

**Comment by martijn00** [comment] 2019-06-08 12:43
Fixed in 0.6.5

**Closed by martijn00** 2019-06-08 12:43 UTC
Labels: bug
