### ISSUE TITLE
Current is not implemented.

### ISSUE THREAD

**Issue by MrSerWin** [martijn00/XamarinMediaManager#437] opened 2019-04-13 15:15 UTC
## 🐛 Bug Report
CrossMediaManager.Current - Current is not implemented.
System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

### Configuration
Xamarin.Forms

**Version:** 0.5.1
**Platform:** 
- [x] :robot: Android

**Comment by o1298098** [comment] 2019-04-13 15:26
+1

**Comment by tonyyyrocks39** [comment] 2019-04-13 18:06
+1

**Comment by MrSerWin** [comment] 2019-04-13 19:04
2.0.0 [/usr/local/share/dotnet/sdk]
2.1.4 [/usr/local/share/dotnet/sdk]
2.1.504 [/usr/local/share/dotnet/sdk]
2.2.102 [/usr/local/share/dotnet/sdk]
2.2.105 [/usr/local/share/dotnet/sdk]
2.2.106 [/usr/local/share/dotnet/sdk]

**Comment by tonyyyrocks39** [comment] 2019-04-14 04:33
Hi ,

could you please fix this .Because this entire library was very good,but now it is nothing for use as in
0.5.1-Gives not implemented exception
0.5.0-same
0.4.5-Cant play/resume or current value change not working in Android,not checked in ios

Thanks,
Tony

**Comment by martijn00** [comment] 2019-04-15 13:58
You need to target Android 9.0 so it won't reference the netstandard in Android. I've also updated to 0.5.3 so it references less dependencies to make it easier.

**Closed by martijn00** 2019-04-15 13:58 UTC

**Comment by tonyyyrocks39** [comment] 2019-04-16 03:46
Not sure ..whether this is actually fixed or not,I am still getting error.
1.Created a new project in Xamarin.Forms(.Net standard),
As of now only a PCL library and Xamarin.Android Project
2.Added only one line code for initialization in mainactivity-
 CrossMediaManager.Current.Init();

3.Targeted to Android 9.0 and minimum is Android 5.0
3.After building it is giving same exception

Attached project file for reference-
https://drive.google.com/open?id=17biZk19HPzxUq2QqPbHV6H2Mo9OoB0Hq
(Need to clean and rebuild)

**Comment by MrSerWin** [comment] 2019-04-16 07:32
I set as target Android 9.0 and installed 5.3 but it does not helped me

**Comment by MrSerWin** [comment] 2019-04-16 07:45
Ah! after clean up and rebuild project it built ok but I have new error on playing audio.
1.call Current.Play() 
2. loading (about 10-20 sec)
3. Unhandled Exception:
Java.Lang.SecurityException: <Timeout exceeded getting exception details> occurred

**Comment by tonyyyrocks39** [comment] 2019-04-16 08:04
even for the first time I got the same exception,but after that same exception not implemented...As per the documentation we need to call Init in mainactivity,but in Init() itself it is giving exception

**Comment by MrSerWin** [comment] 2019-04-16 08:16
@tonyyyrocks39 , try again clean poject or remove bi, obj folders. it helped me with "not implemented " exception

**Comment by tonyyyrocks39** [comment] 2019-04-16 10:36
No,It doesnot work,I have attached the project -
https://drive.google.com/open?id=17biZk19HPzxUq2QqPbHV6H2Mo9OoB0Hq

**Comment by MrSerWin** [comment] 2019-04-16 11:48
@tonyyyrocks39 
1. you use Net standart 1.6.1
2. update xamarin.forms to latest
3. update dependencies for Android project
4. profit

**Comment by tonyyyrocks39** [comment] 2019-04-16 15:49
done everything,still getting error
![Uploading image.png  …]()

**Comment by tonyyyrocks39** [comment] 2019-04-16 15:58
![image](https://user-images.githubusercontent.com/47384824/56224971-1bd3d200-608e-11e9-8938-430366bb6cb7.png)

**Comment by martijn00** [comment] 2019-04-16 16:04
@tonyyyrocks39 I've reproduced the exact same situation, and as said the fix is easy. If you want help open a public repo on Github with a reproduction case, don't put code on Drive.

**Comment by tonyyyrocks39** [comment] 2019-04-16 16:20
I didnot wanted to put codes,but just wondering how come this library was working with older versions but not in latest versions,Also in documentation the main point was Init() method ,there itself if app will crash I am sure this is related to library...not upgrading the Xamarin.Forms

**Comment by tonyyyrocks39** [comment] 2019-04-16 16:24
And I am sure...timeout exception also related to this System.NotImplemented issue...
If the fix is easy..Request you to please tell us...it will save lot of time others

**Comment by martijn00** [comment] 2019-04-16 16:26
@tonyyyrocks39 Please investigate and build up knowledge. This is not a problem in the library.

**Comment by tonyyyrocks39** [comment] 2019-04-16 16:27
sure...

**Comment by tonyyyrocks39** [comment] 2019-04-17 03:39
Though it has been closed prematurely,
but still exists and it is directly related to Library.Find my comment in #443

**Comment by valentin-debris** [comment] 2019-04-17 07:58
@tonyyyrocks39 ,

As @martijn00 says, it's not a problem with this library. I migrate from 0.4.5 to 0.5.3 without any problem for the init.

I also created a dummy repo [(https://github.com/valentin-debris/MediaManagerStates)](https://github.com/valentin-debris/MediaManagerStates) (to show another issue) but if you build it, you will see no problems, so it's not related to the library. Try to remove the bin & obj folder

**Comment by MrSerWin** [comment] 2019-04-17 08:40
@valentin-debris Hi. in your branch  have the same error like in my project. if I set target to 29 

> Unhandled Exception:
> Java.Lang.SecurityException: <Timeout exceeded getting exception details>

**Comment by valentin-debris** [comment] 2019-04-17 08:46
@MrSerWin ,

So the problem is probably with the Android libraries. Try to download the last ones from the SDK Manager.

**Comment by tonyyyrocks39** [comment] 2019-04-17 09:46
@valentin-debris 
even I have same configuration,still giving the exception,tried deleting bin and obj folder,not working,
like I said in another thread it is giving exception line number-27 of MediaManager/CrossMediaManager.cs

**Comment by MrSerWin** [comment] 2019-04-17 09:50
@valentin-debris Can you tell me, why I can't select 29 in android manifest? 
https://ana-yurt.com/uploads/photo/2019-04-17_12-47-54.png
https://ana-yurt.com/uploads/photo/2019-04-17_12-47-54.png

**Comment by valentin-debris** [comment] 2019-04-17 10:04
@MrSerWin 
I'm currently targetting Api 28 (Pie 9.0) so it should be good.. (I can't select 29 neither)

Also, I'm using VS 2019, try to create a dummy project and add the MediaManager, maybe this will install the latest version for somes stuff you have...

**Comment by MrSerWin** [comment] 2019-04-17 10:07
@valentin-debris oh, I was mistaked, I mean 28. I also use VS 2019

**Comment by Muthutc** [comment] 2019-05-19 09:54
Hi @MrSerWin Have You tried this. Is it working for u. Please Let Me Know

**Comment by Muthutc** [comment] 2019-05-19 13:48
Hi @MrSerWin @martijn00 @valentin-debris Is it working in Android Lollipop.

**Comment by sahithisk** [comment] 2021-02-02 11:13
I have followed every step here. But still facing the same issue.

**Comment by msoumare** [comment] 2021-05-16 01:46
@martijn00 

Hi, I'm facing this exception for the past 3 days and I've done everything you recommend to fix this issue but no luck.

I've installed the latest version of the Nuget Package 1.0.8 on all 3 projects (.NET Standard 2.0 Shared, Android and iOS)
I've ensured the Android project is targeting 9.0 (API 28)
I've added CrossMediaManager.Current.Init(); into the Android Project

First off the Readme documentation that's generated after installation is wrong, because it's saying for Android you have to add CrossMediaManager.Current.Init(this); and with the this keyword as a parameter it will not work.  So the only thing that would work is without the this keyword CrossMediaManager.Current.Init(); 

Second, no matter what version of the Nuget Package I still get the Not Implemented Exception.

Would you please shed some light in this error or fix the NugetPackage?

Thanks
