### ISSUE TITLE
BufferingChanged does not fire

### ISSUE THREAD

**Issue by corgalore** [martijn00/XamarinMediaManager#202] opened 2017-05-31 18:47 UTC
I have a basic Xamarin.Forms PCL project in VS 2017, debugging on physical Galaxy S7 Edge device.

With these 2 events wired up, the _BufferingChanged_ event does NOT fire, but the _PlayingChanged_ event DOES fire:

```
CrossMediaManager.Current.BufferingChanged += (sender, e) =>
{
	BufferBar.Progress = e.BufferProgress;
};
CrossMediaManager.Current.PlayingChanged += (sender, e) =>
{
	ProgressBar.Progress = e.Progress * 0.01;
	Duration.Text = "" + e.Duration.TotalSeconds.ToString() + " seconds";
};
```

I set breakpoint inside the _BufferingChanged_ event and it's never hit.

**Comment by BtrJay** [comment] 2017-06-01 06:19
I have tested on Galaxy S6 and had same issue. It seems BufferingChanged not fired at all. Also On StatusChanged event, it seems Status not set to be MediaPlayerStatus.Buffering for Android.

Please see the code below and advise me if you have any workaround/solution to tackle this.

CrossMediaManager.Current.StatusChanged += (sender, e) => {
  if(e.Status ==  MediaPlayerStatus.Buffering){
    //it's never been hit on Android (works on iOS)
  }
};

**Comment by corgalore** [comment] 2017-06-01 15:10
@BtrJay, I can help you with that one. This code works on S6 for me:

```
CrossMediaManager.Current.StatusChanged += (sender, e) =>
{
        State.Text = e.Status.ToString();
};
```

Try just reading the e.Status string.

**Comment by BtrJay** [comment] 2017-07-03 01:17
Hi @corgalore , thanks for your suggestion.

It looks like StatusChanged is firing for mp4, but not for mp3 when I tested it out.

I've tested it on Samsung Galaxy Tab.

Have you seen this issue at your end?

**Comment by Ruddy2007** [comment] 2017-11-07 13:34
Buffering is never hit after the first load. If you seek etc it never gets hit. We kind of need this to tell the user it is buffing. Any fix?

**Comment by BtrJay** [comment] 2017-11-08 00:36
@Ruddy2007, I think I've got an fix and will create a PR shortly. The issue is more related to #215 I will close this off

**Closed** 2019-04-05 14:21 UTC
