### ISSUE TITLE
Xamarin.Forms - Android - Play Http video / Local file video - Call to getEmbeddedPicture failed.

### ISSUE THREAD

**Issue by david-abaev** [martijn00/XamarinMediaManager#332] opened 2017-12-25 23:02 UTC
Hello. So I cant fix this issue:
[MediaMetadataRetrieverJNI] getEmbeddedPicture: Call to getEmbeddedPicture failed.

My "build"
Xamarin.Android packages 23.3.0
Xamarin Forms 2.5.0.12
MediaManager and Xamarin Media Manager 0.4.5

On IOS -Everything work Fine! 

On android:
[MediaMetadataRetrieverJNI] getEmbeddedPicture: Call to getEmbeddedPicture failed.

I try play Local file
Path for example:
/storage/emulated/0/Project-app/Project-App-Video-1272.mp4
CrossMediaManager.Current.Play("file://" + filePath); // For play local file I'm added 'file://'

I try play video by url
CrossMediaManager.Current.Play('http://.........')

Same issue on both ways :(

Again - On IOS everything work well.

Please help!! :(

**Comment by Immons** [comment] 2018-08-08 09:58
Regarding this problem (yea, I know it's quite old). I noticed that page on Android loads slower, and if we set source too early, VideoView doesn't get loaded yet and then blocks even Current.Play. For me it could be noticed that it started to work if I added Task.Delay(1000) before setting source.

**Comment by martijn00** [comment] 2018-08-08 10:01
This will be fixed in v1.0.

**Comment by raghuyt** [comment] 2018-12-12 07:45
Hi @martijn00  ,@david-abaev 

Am storing videos on my local project resources folder in IOS, i want play that local video using  your plugin (XamarinMediaManager)
Can you please give some examples  ?

Thank you in advance

**Closed** 2019-04-05 14:21 UTC

**Comment by marcelovargas** [comment] 2019-07-14 22:50
Please some examples of local videos

**Comment by lubiepomaranczki** [comment] 2020-05-30 11:50
@martijn00 This still happens when using version 0.9.0 in Forms 4.5.0.356. Android is not working, iOS works fine. 
To reproduce it, you can either check my [sample repository](https://github.com/lubiepomaranczki/XamarinMediaManagerTest/blob/master/Test/MainPage.xaml.cs) or add control to your XAML and in CodeBehind do
```csharp
protected override void OnAppearing()
{
    base.OnAppearing();

    CrossMediaManager.Current.Play(new MediaItem("https://vjs.zencdn.net/v/oceans.mp4"));
}
```
As stated above, only Android is affected.

Applying Artur's "fix" (`Task.Delay(1000)`) solves the problem. But the issue is still there
