### ISSUE TITLE
PlaybackController Pause dose not retaine the duration

### ISSUE THREAD

**Issue by AlenToma** [martijn00/XamarinMediaManager#511] opened 2019-06-30 14:41 UTC
## 🐛 Bug Report

When toggling pause/play the duration is lost and the video start from the start for my custom controller
### Expected behavior
When clicked play after the player has been paused, it should continue from the last duration.
### Reproduction steps
* It a custom renderer, here is my code 

```
     private IPlaybackManager PlaybackController => CrossMediaManager.Current;
     public async void TogglePlay(object sender, EventArgs arg)
        {
            if (MediaPlayer.IsPlaying())
                await PlaybackController.Pause();
            else await PlaybackController.Play();
        }
```
### Configuration

**Version:** 0.6.7

**Platform:** 
- [ ] :robot: Android
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment] 2019-06-30 14:57
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/504

**Comment by martijn00** [comment] 2019-06-30 14:57
I need to debug this sometime, but don't have so much time to work on it at the moment.

**Closed by martijn00** 2019-06-30 14:57 UTC

**Comment by AlenToma** [comment] 2019-06-30 15:13
For those in need, here is a simple workout

```
private IPlaybackManager PlaybackController => CrossMediaManager.Current;
  public async void TogglePlay(object sender, EventArgs arg)
        {
            if (MediaPlayer.State == MediaPlayerState.Playing)
            {
                _prevDuration = MediaPlayer.Position; // Save the current duration
                await PlaybackController.Pause();

            }
            else
            {
                await PlaybackController.Play();
            }
        }
```

```
      private async void PlaybackController_StateChanged(object sender, StateChangedEventArgs e)
        {
            switch (e.State)
            {
                case MediaPlayerState.Playing:
                    if (_prevDuration != null)
                    {
                        await PlaybackController.SeekTo(_prevDuration.Value); // play from the prev duration
                        _prevDuration = null;
                    }
                    CheckState();
                    btnPlay.SetImageResource(Resource.Drawable.ic_pause_36dp);
                    break;

                case MediaPlayerState.Paused:
                    btnPlay.SetImageResource(Resource.Drawable.ic_play_36dp);
                    break;
            }
        }
```

**Comment by martijn00** [comment] 2019-06-30 15:25
@AlenToma are you able to debug the source code, and maybe provide a fix there?

**Comment by AlenToma** [comment] 2019-06-30 15:31
I would, but im really new to `xamarin.forms`. and i have only worked with android untill now.

If you are comfortable enough with that, then its no problem for me.

**Comment by martijn00** [comment] 2019-06-30 15:32
Yeah no problem, i would love to get some extra help on those sort of bug fixes. Let me know if you need information on anything.

The Android part of the codebase is probably to most complex, so it helps if you have experience with that.

**Comment by AlenToma** [comment] 2019-06-30 15:34
Ok, should i fork this project and then post the solution here, or will you give premission to it?

**Comment by martijn00** [comment] 2019-06-30 15:36
Yes you should fork the project, commit a fix on a branch in your fork and then make a pull request on this repo. After that i review it and merge if there are no problems.

If you have questions about it, you can also ping me on slack: https://xamarinchat.herokuapp.com/

**Comment by AlenToma** [comment] 2019-06-30 17:30
I have fixed the issue in my branch and created a pull requast.

When you fix or add code to your project, can i just refork it agen and i get all the changes. 

How do i get the changes you will make to my fork later ?

**Comment by martijn00** [comment] 2019-06-30 19:18
@AlenToma thanks! I'll have a look soon. After i merge the PR you need to pull in the changes into your fork. You do this by adding a second "remote" to your git locally. This remote is my repo, and when you have done that you can either pull my develop branch again and push it to your own remote fork, or merge it into your own branch and push it.
