### ISSUE TITLE
CrossMediaManager.Current.Init no parameter

### ISSUE THREAD

**Issue by mmehdidehghani** [martijn00/XamarinMediaManager#485] opened 2019-05-27 08:04 UTC
I installed Plugin.MediaManager.Forms 0.6 in my Xamarin.Forms project.
When i want to add CrossMediaManager.Current.Init(this) in the MainActivity, I get the this error:
error message : Method int() has 0 parameter(s) but is invoked with 1 argument(s)

Could you please help me?

**Comment by mmehdidehghani** [comment] 2019-05-27 08:07
error message : Method int() has 0 parameter(s) but is invoked with 1 argument(s)

**Comment by martijn00** [comment] 2019-05-27 08:25
Probably duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437

You need to target android 9.0

**Closed** 2019-05-27 14:58 UTC

**Comment by EliasSalom** [comment] 2020-03-11 20:38
I also have the same problem and my target android is 9.0

**Comment by martijn00** [comment] 2020-03-11 21:00
Now you need to target v10.0.

**Comment by hansmerdijk** [comment] 2020-03-24 21:26
target to v10.0 does not solve the problem, call init with (this) gives error while building, call init with () does start the emulator but it crashes as soon as it starts up.

**Comment by francoisdutoit** [comment] 2020-04-01 14:07
> target to v10.0 does not solve the problem, call init with (this) gives error while building, call init with () does start the emulator but it crashes as soon as it starts up.

+1

**Comment by junior-pires** [comment] 2020-05-14 22:26
I already target to v10.0 but I still facing the issue @martijn00  help plzzz

**Comment by eclipsed4utoo** [comment] 2020-05-19 01:45
Just confirming that updating to the latest release of this library will break your application on Android. Found out the hard way tonight.

Targetting v9 or v10 doesn't matter. There is no available method `CrossCurrentMedia.Current.Init(Context)`. Using the `Init` method throws an exception at runtime.

I'm going to rollback version by version until it starts working again. I know version 0.8.18 works since that's what I upgraded from.

**Comment by junior-pires** [comment] 2020-05-19 10:12
yes, targeting to v9 or v10 doesn't work. I rollback to version 0.9.0 and
it's working fine

Ryan Alford <notifications@github.com> escreveu no dia terça, 19/05/2020
à(s) 03:46:

**Comment by k0steash** [comment] 2020-11-23 19:14
Last Version, was working for me, is 0.9.6
