### ISSUE TITLE
Xamarin Android: This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by PingPongSet** [martijn00/XamarinMediaManager#466] opened 2019-04-29 23:07 UTC
I have got an error below:

> Unhandled Exception:
> 
> System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation. occurred
> 

NuGet package: 

```
 <PackageReference Include="Plugin.MediaManager">
      <Version>0.5.4</Version>
    </PackageReference>
```

 ```
[Application(Label = "@string/app_name")]
    public class Application: Android.App.Application
    {
        public Application(IntPtr javaReference, JniHandleOwnership transfer)
           : base(javaReference, transfer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            CrossMediaManager.Current.Init();

        }      
    }

```

I have got the same error, when  `CrossMediaManager.Current.Init();` is used on OnCreate of an activity.

**Comment by martijn00** [comment] 2019-04-30 08:16
Duplicate of https://github.com/martijn00/XamarinMediaManager/issues/437

**Closed by martijn00** 2019-04-30 08:16 UTC
